//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GISCore.WSAutenticacao {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CartaoCorporativoSoap", Namespace="http://tempuri.org/")]
    public partial class CartaoCorporativo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarFaturasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarDespesasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalvarDadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarFaturasAbastecimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarDespesasAbastecimentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CartaoCorporativo() {
            this.Url = global::GISCore.Properties.Settings.Default.GISCore_WSAutenticacao_CartaoCorporativo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event BuscarFaturasCompletedEventHandler BuscarFaturasCompleted;
        
        /// <remarks/>
        public event BuscarDespesasCompletedEventHandler BuscarDespesasCompleted;
        
        /// <remarks/>
        public event SalvarDadosCompletedEventHandler SalvarDadosCompleted;
        
        /// <remarks/>
        public event BuscarFaturasAbastecimentoCompletedEventHandler BuscarFaturasAbastecimentoCompleted;
        
        /// <remarks/>
        public event BuscarDespesasAbastecimentoCompletedEventHandler BuscarDespesasAbastecimentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string pMatricula, string pSenha) {
            object[] results = this.Invoke("Login", new object[] {
                        pMatricula,
                        pSenha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string pMatricula, string pSenha) {
            this.LoginAsync(pMatricula, pSenha, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string pMatricula, string pSenha, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        pMatricula,
                        pSenha}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarFaturas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscarFaturas(string Matricula) {
            object[] results = this.Invoke("BuscarFaturas", new object[] {
                        Matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarFaturasAsync(string Matricula) {
            this.BuscarFaturasAsync(Matricula, null);
        }
        
        /// <remarks/>
        public void BuscarFaturasAsync(string Matricula, object userState) {
            if ((this.BuscarFaturasOperationCompleted == null)) {
                this.BuscarFaturasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarFaturasOperationCompleted);
            }
            this.InvokeAsync("BuscarFaturas", new object[] {
                        Matricula}, this.BuscarFaturasOperationCompleted, userState);
        }
        
        private void OnBuscarFaturasOperationCompleted(object arg) {
            if ((this.BuscarFaturasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarFaturasCompleted(this, new BuscarFaturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarDespesas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscarDespesas(string OBID) {
            object[] results = this.Invoke("BuscarDespesas", new object[] {
                        OBID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarDespesasAsync(string OBID) {
            this.BuscarDespesasAsync(OBID, null);
        }
        
        /// <remarks/>
        public void BuscarDespesasAsync(string OBID, object userState) {
            if ((this.BuscarDespesasOperationCompleted == null)) {
                this.BuscarDespesasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarDespesasOperationCompleted);
            }
            this.InvokeAsync("BuscarDespesas", new object[] {
                        OBID}, this.BuscarDespesasOperationCompleted, userState);
        }
        
        private void OnBuscarDespesasOperationCompleted(object arg) {
            if ((this.BuscarDespesasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarDespesasCompleted(this, new BuscarDespesasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SalvarDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SalvarDados([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Content, string FileName, string CentroCusto, string Quantidade, string Justificativa, string OBID) {
            object[] results = this.Invoke("SalvarDados", new object[] {
                        Content,
                        FileName,
                        CentroCusto,
                        Quantidade,
                        Justificativa,
                        OBID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SalvarDadosAsync(byte[] Content, string FileName, string CentroCusto, string Quantidade, string Justificativa, string OBID) {
            this.SalvarDadosAsync(Content, FileName, CentroCusto, Quantidade, Justificativa, OBID, null);
        }
        
        /// <remarks/>
        public void SalvarDadosAsync(byte[] Content, string FileName, string CentroCusto, string Quantidade, string Justificativa, string OBID, object userState) {
            if ((this.SalvarDadosOperationCompleted == null)) {
                this.SalvarDadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarDadosOperationCompleted);
            }
            this.InvokeAsync("SalvarDados", new object[] {
                        Content,
                        FileName,
                        CentroCusto,
                        Quantidade,
                        Justificativa,
                        OBID}, this.SalvarDadosOperationCompleted, userState);
        }
        
        private void OnSalvarDadosOperationCompleted(object arg) {
            if ((this.SalvarDadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarDadosCompleted(this, new SalvarDadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarFaturasAbastecimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscarFaturasAbastecimento(string Matricula) {
            object[] results = this.Invoke("BuscarFaturasAbastecimento", new object[] {
                        Matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarFaturasAbastecimentoAsync(string Matricula) {
            this.BuscarFaturasAbastecimentoAsync(Matricula, null);
        }
        
        /// <remarks/>
        public void BuscarFaturasAbastecimentoAsync(string Matricula, object userState) {
            if ((this.BuscarFaturasAbastecimentoOperationCompleted == null)) {
                this.BuscarFaturasAbastecimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarFaturasAbastecimentoOperationCompleted);
            }
            this.InvokeAsync("BuscarFaturasAbastecimento", new object[] {
                        Matricula}, this.BuscarFaturasAbastecimentoOperationCompleted, userState);
        }
        
        private void OnBuscarFaturasAbastecimentoOperationCompleted(object arg) {
            if ((this.BuscarFaturasAbastecimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarFaturasAbastecimentoCompleted(this, new BuscarFaturasAbastecimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarDespesasAbastecimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscarDespesasAbastecimento(string OBID) {
            object[] results = this.Invoke("BuscarDespesasAbastecimento", new object[] {
                        OBID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarDespesasAbastecimentoAsync(string OBID) {
            this.BuscarDespesasAbastecimentoAsync(OBID, null);
        }
        
        /// <remarks/>
        public void BuscarDespesasAbastecimentoAsync(string OBID, object userState) {
            if ((this.BuscarDespesasAbastecimentoOperationCompleted == null)) {
                this.BuscarDespesasAbastecimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarDespesasAbastecimentoOperationCompleted);
            }
            this.InvokeAsync("BuscarDespesasAbastecimento", new object[] {
                        OBID}, this.BuscarDespesasAbastecimentoOperationCompleted, userState);
        }
        
        private void OnBuscarDespesasAbastecimentoOperationCompleted(object arg) {
            if ((this.BuscarDespesasAbastecimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarDespesasAbastecimentoCompleted(this, new BuscarDespesasAbastecimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BuscarFaturasCompletedEventHandler(object sender, BuscarFaturasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarFaturasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarFaturasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BuscarDespesasCompletedEventHandler(object sender, BuscarDespesasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarDespesasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarDespesasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SalvarDadosCompletedEventHandler(object sender, SalvarDadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SalvarDadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SalvarDadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BuscarFaturasAbastecimentoCompletedEventHandler(object sender, BuscarFaturasAbastecimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarFaturasAbastecimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarFaturasAbastecimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BuscarDespesasAbastecimentoCompletedEventHandler(object sender, BuscarDespesasAbastecimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarDespesasAbastecimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarDespesasAbastecimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591