//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISCore.CEMIGInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosEmpregado", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class DadosEmpregado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveAcessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IgnorarDesligamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ChaveAcesso {
            get {
                return this.ChaveAcessoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveAcessoField, value) != true)) {
                    this.ChaveAcessoField = value;
                    this.RaisePropertyChanged("ChaveAcesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IgnorarDesligamento {
            get {
                return this.IgnorarDesligamentoField;
            }
            set {
                if ((this.IgnorarDesligamentoField.Equals(value) != true)) {
                    this.IgnorarDesligamentoField = value;
                    this.RaisePropertyChanged("IgnorarDesligamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultInterop", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class FaultInterop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosOrgao", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class DadosOrgao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sigla {
            get {
                return this.SiglaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaField, value) != true)) {
                    this.SiglaField = value;
                    this.RaisePropertyChanged("Sigla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UA {
            get {
                return this.UAField;
            }
            set {
                if ((object.ReferenceEquals(this.UAField, value) != true)) {
                    this.UAField = value;
                    this.RaisePropertyChanged("UA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orgao", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class Orgao : GISCore.CEMIGInfoService.DBINFOBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Aprovador[] AprovadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelHierarquicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularMatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UASuperiorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Aprovador[] Aprovadores {
            get {
                return this.AprovadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.AprovadoresField, value) != true)) {
                    this.AprovadoresField = value;
                    this.RaisePropertyChanged("Aprovadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NivelHierarquico {
            get {
                return this.NivelHierarquicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelHierarquicoField, value) != true)) {
                    this.NivelHierarquicoField = value;
                    this.RaisePropertyChanged("NivelHierarquico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeCompleto {
            get {
                return this.NomeCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCompletoField, value) != true)) {
                    this.NomeCompletoField = value;
                    this.RaisePropertyChanged("NomeCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sigla {
            get {
                return this.SiglaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaField, value) != true)) {
                    this.SiglaField = value;
                    this.RaisePropertyChanged("Sigla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TitularMatricula {
            get {
                return this.TitularMatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularMatriculaField, value) != true)) {
                    this.TitularMatriculaField = value;
                    this.RaisePropertyChanged("TitularMatricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TitularNome {
            get {
                return this.TitularNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularNomeField, value) != true)) {
                    this.TitularNomeField = value;
                    this.RaisePropertyChanged("TitularNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UA {
            get {
                return this.UAField;
            }
            set {
                if ((object.ReferenceEquals(this.UAField, value) != true)) {
                    this.UAField = value;
                    this.RaisePropertyChanged("UA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UASuperior {
            get {
                return this.UASuperiorField;
            }
            set {
                if ((object.ReferenceEquals(this.UASuperiorField, value) != true)) {
                    this.UASuperiorField = value;
                    this.RaisePropertyChanged("UASuperior");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBINFOBase", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GISCore.CEMIGInfoService.Empresa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GISCore.CEMIGInfoService.Empregado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GISCore.CEMIGInfoService.Orgao))]
    public partial class DBINFOBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class Empresa : GISCore.CEMIGInfoService.DBINFOBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empregado", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class Empregado : GISCore.CEMIGInfoService.DBINFOBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DesligadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Empresa EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Numero_EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Orgao OrgaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionalField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Desligado {
            get {
                return this.DesligadoField;
            }
            set {
                if ((this.DesligadoField.Equals(value) != true)) {
                    this.DesligadoField = value;
                    this.RaisePropertyChanged("Desligado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Numero_Endereco {
            get {
                return this.Numero_EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.Numero_EnderecoField, value) != true)) {
                    this.Numero_EnderecoField = value;
                    this.RaisePropertyChanged("Numero_Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Orgao Orgao {
            get {
                return this.OrgaoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgaoField, value) != true)) {
                    this.OrgaoField = value;
                    this.RaisePropertyChanged("Orgao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Regional {
            get {
                return this.RegionalField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionalField, value) != true)) {
                    this.RegionalField = value;
                    this.RaisePropertyChanged("Regional");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aprovador", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class Aprovador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Regional {
            get {
                return this.RegionalField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionalField, value) != true)) {
                    this.RegionalField = value;
                    this.RaisePropertyChanged("Regional");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosContratoConsulta", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class DadosContratoConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.DadosOrgao OrgaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SomenteValidosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fornecedor {
            get {
                return this.FornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorField, value) != true)) {
                    this.FornecedorField = value;
                    this.RaisePropertyChanged("Fornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.DadosOrgao Orgao {
            get {
                return this.OrgaoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgaoField, value) != true)) {
                    this.OrgaoField = value;
                    this.RaisePropertyChanged("Orgao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool SomenteValidos {
            get {
                return this.SomenteValidosField;
            }
            set {
                if ((this.SomenteValidosField.Equals(value) != true)) {
                    this.SomenteValidosField = value;
                    this.RaisePropertyChanged("SomenteValidos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contrato", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class Contrato : GISCore.CEMIGInfoService.EntidadeBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Orgao DiretoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Fornecedor FornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Orgao GerenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Orgao RequisitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.Orgao SuperintendenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DataFim {
            get {
                return this.DataFimField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFimField, value) != true)) {
                    this.DataFimField = value;
                    this.RaisePropertyChanged("DataFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DataInicio {
            get {
                return this.DataInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.DataInicioField, value) != true)) {
                    this.DataInicioField = value;
                    this.RaisePropertyChanged("DataInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Orgao Diretoria {
            get {
                return this.DiretoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiretoriaField, value) != true)) {
                    this.DiretoriaField = value;
                    this.RaisePropertyChanged("Diretoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Fornecedor Fornecedor {
            get {
                return this.FornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorField, value) != true)) {
                    this.FornecedorField = value;
                    this.RaisePropertyChanged("Fornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Orgao Gerencia {
            get {
                return this.GerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.GerenciaField, value) != true)) {
                    this.GerenciaField = value;
                    this.RaisePropertyChanged("Gerencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Objeto {
            get {
                return this.ObjetoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjetoField, value) != true)) {
                    this.ObjetoField = value;
                    this.RaisePropertyChanged("Objeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Orgao Requisitante {
            get {
                return this.RequisitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.RequisitanteField, value) != true)) {
                    this.RequisitanteField = value;
                    this.RaisePropertyChanged("Requisitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.Orgao Superintendencia {
            get {
                return this.SuperintendenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SuperintendenciaField, value) != true)) {
                    this.SuperintendenciaField = value;
                    this.RaisePropertyChanged("Superintendencia");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadeBase", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GISCore.CEMIGInfoService.Fornecedor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GISCore.CEMIGInfoService.NS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GISCore.CEMIGInfoService.Aplicacao))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GISCore.CEMIGInfoService.Contrato))]
    public partial class EntidadeBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fornecedor", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class Fornecedor : GISCore.CEMIGInfoService.EntidadeBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GISCore.CEMIGInfoService.SituacaoFornecedor SituacaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Bloqueado {
            get {
                return this.BloqueadoField;
            }
            set {
                if ((this.BloqueadoField.Equals(value) != true)) {
                    this.BloqueadoField = value;
                    this.RaisePropertyChanged("Bloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GISCore.CEMIGInfoService.SituacaoFornecedor Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((this.SituacaoField.Equals(value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NS", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class NS : GISCore.CEMIGInfoService.EntidadeBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AREA_OPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_MUNICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string END_EXTENSOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string END_RURALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCALIZACAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCAL_OBJ_PMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOME_BAIRROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOME_MUNICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_NSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_EDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POLOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TELS_PNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEL_FIXOField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AREA_OP {
            get {
                return this.AREA_OPField;
            }
            set {
                if ((object.ReferenceEquals(this.AREA_OPField, value) != true)) {
                    this.AREA_OPField = value;
                    this.RaisePropertyChanged("AREA_OP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string COD_MUNIC {
            get {
                return this.COD_MUNICField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_MUNICField, value) != true)) {
                    this.COD_MUNICField = value;
                    this.RaisePropertyChanged("COD_MUNIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string END_EXTENSO {
            get {
                return this.END_EXTENSOField;
            }
            set {
                if ((object.ReferenceEquals(this.END_EXTENSOField, value) != true)) {
                    this.END_EXTENSOField = value;
                    this.RaisePropertyChanged("END_EXTENSO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string END_RURAL {
            get {
                return this.END_RURALField;
            }
            set {
                if ((object.ReferenceEquals(this.END_RURALField, value) != true)) {
                    this.END_RURALField = value;
                    this.RaisePropertyChanged("END_RURAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LOCALIZACAO {
            get {
                return this.LOCALIZACAOField;
            }
            set {
                if ((object.ReferenceEquals(this.LOCALIZACAOField, value) != true)) {
                    this.LOCALIZACAOField = value;
                    this.RaisePropertyChanged("LOCALIZACAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LOCAL_OBJ_PM {
            get {
                return this.LOCAL_OBJ_PMField;
            }
            set {
                if ((object.ReferenceEquals(this.LOCAL_OBJ_PMField, value) != true)) {
                    this.LOCAL_OBJ_PMField = value;
                    this.RaisePropertyChanged("LOCAL_OBJ_PM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOME {
            get {
                return this.NOMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEField, value) != true)) {
                    this.NOMEField = value;
                    this.RaisePropertyChanged("NOME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOME_BAIRRO {
            get {
                return this.NOME_BAIRROField;
            }
            set {
                if ((object.ReferenceEquals(this.NOME_BAIRROField, value) != true)) {
                    this.NOME_BAIRROField = value;
                    this.RaisePropertyChanged("NOME_BAIRRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOME_MUNIC {
            get {
                return this.NOME_MUNICField;
            }
            set {
                if ((object.ReferenceEquals(this.NOME_MUNICField, value) != true)) {
                    this.NOME_MUNICField = value;
                    this.RaisePropertyChanged("NOME_MUNIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NUMERO_NS {
            get {
                return this.NUMERO_NSField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_NSField, value) != true)) {
                    this.NUMERO_NSField = value;
                    this.RaisePropertyChanged("NUMERO_NS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NUM_EDF {
            get {
                return this.NUM_EDFField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_EDFField, value) != true)) {
                    this.NUM_EDFField = value;
                    this.RaisePropertyChanged("NUM_EDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string POLO {
            get {
                return this.POLOField;
            }
            set {
                if ((object.ReferenceEquals(this.POLOField, value) != true)) {
                    this.POLOField = value;
                    this.RaisePropertyChanged("POLO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] TELS_PN {
            get {
                return this.TELS_PNField;
            }
            set {
                if ((object.ReferenceEquals(this.TELS_PNField, value) != true)) {
                    this.TELS_PNField = value;
                    this.RaisePropertyChanged("TELS_PN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TEL_FIXO {
            get {
                return this.TEL_FIXOField;
            }
            set {
                if ((object.ReferenceEquals(this.TEL_FIXOField, value) != true)) {
                    this.TEL_FIXOField = value;
                    this.RaisePropertyChanged("TEL_FIXO");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aplicacao", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class Aplicacao : GISCore.CEMIGInfoService.EntidadeBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SituacaoFornecedor", Namespace="http://gedoc2/INTEROP")]
    public enum SituacaoFornecedor : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATIVO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BLOQUEADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ELIMINADO = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosNS", Namespace="http://gedoc2/INTEROP")]
    [System.SerializableAttribute()]
    public partial class DadosNS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gedoc2/INTEROP", ConfigurationName="CEMIGInfoService.InfoService")]
    public interface InfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/EmpregadoEValidador", ReplyAction="http://gedoc2/INTEROP/InfoService/EmpregadoEValidadorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/EmpregadoEValidadorFaultInteropFault", Name="FaultInterop")]
        bool EmpregadoEValidador(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/EmpregadoEValidador", ReplyAction="http://gedoc2/INTEROP/InfoService/EmpregadoEValidadorResponse")]
        System.Threading.Tasks.Task<bool> EmpregadoEValidadorAsync(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarAprovadoresPorOrgao", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarAprovadoresPorOrgaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/ListarAprovadoresPorOrgaoFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Orgao[] ListarAprovadoresPorOrgao(GISCore.CEMIGInfoService.DadosOrgao dadosorgao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarAprovadoresPorOrgao", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarAprovadoresPorOrgaoResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Orgao[]> ListarAprovadoresPorOrgaoAsync(GISCore.CEMIGInfoService.DadosOrgao dadosorgao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarContratos", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarContratosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/ListarContratosFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Contrato[] ListarContratos(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarContratos", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarContratosResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Contrato[]> ListarContratosAsync(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarDadosAplicacoes", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarDadosAplicacoesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/ListarDadosAplicacoesFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Aplicacao[] ListarDadosAplicacoes(string aplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarDadosAplicacoes", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarDadosAplicacoesResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Aplicacao[]> ListarDadosAplicacoesAsync(string aplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarFornecedores", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarFornecedoresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/ListarFornecedoresFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Fornecedor[] ListarFornecedores(string fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarFornecedores", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarFornecedoresResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Fornecedor[]> ListarFornecedoresAsync(string fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarOrgaos", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarOrgaosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/ListarOrgaosFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Orgao[] ListarOrgaos(GISCore.CEMIGInfoService.DadosOrgao dadosOrgaoRaiz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarOrgaos", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarOrgaosResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Orgao[]> ListarOrgaosAsync(GISCore.CEMIGInfoService.DadosOrgao dadosOrgaoRaiz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarValidadoresPorEmpregado", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarValidadoresPorEmpregadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/ListarValidadoresPorEmpregadoFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Empregado[] ListarValidadoresPorEmpregado(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/ListarValidadoresPorEmpregado", ReplyAction="http://gedoc2/INTEROP/InfoService/ListarValidadoresPorEmpregadoResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Empregado[]> ListarValidadoresPorEmpregadoAsync(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosContrato", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosContratoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosContratoFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Contrato RecuperarDadosContrato(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosContrato", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosContratoResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Contrato> RecuperarDadosContratoAsync(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosEmpregado", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosEmpregadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosEmpregadoFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Empregado RecuperarDadosEmpregado(GISCore.CEMIGInfoService.DadosEmpregado dadosempregado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosEmpregado", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosEmpregadoResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Empregado> RecuperarDadosEmpregadoAsync(GISCore.CEMIGInfoService.DadosEmpregado dadosempregado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosFornecedor", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosFornecedorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosFornecedorFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Fornecedor RecuperarDadosFornecedor(string fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosFornecedor", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosFornecedorResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Fornecedor> RecuperarDadosFornecedorAsync(string fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosNS", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosNSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosNSFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.NS RecuperarDadosNS(GISCore.CEMIGInfoService.DadosNS dadosNS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosNS", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosNSResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.NS> RecuperarDadosNSAsync(GISCore.CEMIGInfoService.DadosNS dadosNS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosOrgao", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosOrgaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GISCore.CEMIGInfoService.FaultInterop), Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosOrgaoFaultInteropFault", Name="FaultInterop")]
        GISCore.CEMIGInfoService.Orgao RecuperarDadosOrgao(GISCore.CEMIGInfoService.DadosOrgao dadosOrgao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gedoc2/INTEROP/InfoService/RecuperarDadosOrgao", ReplyAction="http://gedoc2/INTEROP/InfoService/RecuperarDadosOrgaoResponse")]
        System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Orgao> RecuperarDadosOrgaoAsync(GISCore.CEMIGInfoService.DadosOrgao dadosOrgao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InfoServiceChannel : GISCore.CEMIGInfoService.InfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoServiceClient : System.ServiceModel.ClientBase<GISCore.CEMIGInfoService.InfoService>, GISCore.CEMIGInfoService.InfoService {
        
        public InfoServiceClient() {
        }
        
        public InfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EmpregadoEValidador(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado) {
            return base.Channel.EmpregadoEValidador(dadosEmpregado);
        }
        
        public System.Threading.Tasks.Task<bool> EmpregadoEValidadorAsync(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado) {
            return base.Channel.EmpregadoEValidadorAsync(dadosEmpregado);
        }
        
        public GISCore.CEMIGInfoService.Orgao[] ListarAprovadoresPorOrgao(GISCore.CEMIGInfoService.DadosOrgao dadosorgao) {
            return base.Channel.ListarAprovadoresPorOrgao(dadosorgao);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Orgao[]> ListarAprovadoresPorOrgaoAsync(GISCore.CEMIGInfoService.DadosOrgao dadosorgao) {
            return base.Channel.ListarAprovadoresPorOrgaoAsync(dadosorgao);
        }
        
        public GISCore.CEMIGInfoService.Contrato[] ListarContratos(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato) {
            return base.Channel.ListarContratos(dadosContrato);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Contrato[]> ListarContratosAsync(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato) {
            return base.Channel.ListarContratosAsync(dadosContrato);
        }
        
        public GISCore.CEMIGInfoService.Aplicacao[] ListarDadosAplicacoes(string aplicacao) {
            return base.Channel.ListarDadosAplicacoes(aplicacao);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Aplicacao[]> ListarDadosAplicacoesAsync(string aplicacao) {
            return base.Channel.ListarDadosAplicacoesAsync(aplicacao);
        }
        
        public GISCore.CEMIGInfoService.Fornecedor[] ListarFornecedores(string fornecedor) {
            return base.Channel.ListarFornecedores(fornecedor);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Fornecedor[]> ListarFornecedoresAsync(string fornecedor) {
            return base.Channel.ListarFornecedoresAsync(fornecedor);
        }
        
        public GISCore.CEMIGInfoService.Orgao[] ListarOrgaos(GISCore.CEMIGInfoService.DadosOrgao dadosOrgaoRaiz) {
            return base.Channel.ListarOrgaos(dadosOrgaoRaiz);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Orgao[]> ListarOrgaosAsync(GISCore.CEMIGInfoService.DadosOrgao dadosOrgaoRaiz) {
            return base.Channel.ListarOrgaosAsync(dadosOrgaoRaiz);
        }
        
        public GISCore.CEMIGInfoService.Empregado[] ListarValidadoresPorEmpregado(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado) {
            return base.Channel.ListarValidadoresPorEmpregado(dadosEmpregado);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Empregado[]> ListarValidadoresPorEmpregadoAsync(GISCore.CEMIGInfoService.DadosEmpregado dadosEmpregado) {
            return base.Channel.ListarValidadoresPorEmpregadoAsync(dadosEmpregado);
        }
        
        public GISCore.CEMIGInfoService.Contrato RecuperarDadosContrato(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato) {
            return base.Channel.RecuperarDadosContrato(dadosContrato);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Contrato> RecuperarDadosContratoAsync(GISCore.CEMIGInfoService.DadosContratoConsulta dadosContrato) {
            return base.Channel.RecuperarDadosContratoAsync(dadosContrato);
        }
        
        public GISCore.CEMIGInfoService.Empregado RecuperarDadosEmpregado(GISCore.CEMIGInfoService.DadosEmpregado dadosempregado) {
            return base.Channel.RecuperarDadosEmpregado(dadosempregado);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Empregado> RecuperarDadosEmpregadoAsync(GISCore.CEMIGInfoService.DadosEmpregado dadosempregado) {
            return base.Channel.RecuperarDadosEmpregadoAsync(dadosempregado);
        }
        
        public GISCore.CEMIGInfoService.Fornecedor RecuperarDadosFornecedor(string fornecedor) {
            return base.Channel.RecuperarDadosFornecedor(fornecedor);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Fornecedor> RecuperarDadosFornecedorAsync(string fornecedor) {
            return base.Channel.RecuperarDadosFornecedorAsync(fornecedor);
        }
        
        public GISCore.CEMIGInfoService.NS RecuperarDadosNS(GISCore.CEMIGInfoService.DadosNS dadosNS) {
            return base.Channel.RecuperarDadosNS(dadosNS);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.NS> RecuperarDadosNSAsync(GISCore.CEMIGInfoService.DadosNS dadosNS) {
            return base.Channel.RecuperarDadosNSAsync(dadosNS);
        }
        
        public GISCore.CEMIGInfoService.Orgao RecuperarDadosOrgao(GISCore.CEMIGInfoService.DadosOrgao dadosOrgao) {
            return base.Channel.RecuperarDadosOrgao(dadosOrgao);
        }
        
        public System.Threading.Tasks.Task<GISCore.CEMIGInfoService.Orgao> RecuperarDadosOrgaoAsync(GISCore.CEMIGInfoService.DadosOrgao dadosOrgao) {
            return base.Channel.RecuperarDadosOrgaoAsync(dadosOrgao);
        }
    }
}
